---
title: Bluemonkey1130.Github.Io
timezone: UTC
collections:
  people:
    title: People
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Hank Quinlan, Horrible Cop
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title"
